"""
Enforcement Service — DMCA Generation & Evidence Packaging

Generates properly structured DMCA takedown notices,
cease-and-desist letters, and evidence packages.
"""

import json
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

DMCA_TEMPLATE = """DMCA TAKEDOWN NOTICE
pursuant to 17 U.S.C. § 512(c)

Date: {date}
Reference ID: AEGIS-{ref_id}

To: {platform} Copyright/Legal Department

RE: Infringement of Copyrighted Sports Media Content

I. IDENTIFICATION OF COPYRIGHTED WORK
The copyrighted work being infringed is:
- Asset Name: {asset_name}
- Original Registration Date: {registration_date}
- Content Description: {description}
- Rights Holder: {rights_holder}

II. IDENTIFICATION OF INFRINGING MATERIAL
The infringing material is located at:
- URL: {infringing_url}
- Platform: {platform}
- Detection Date: {detection_date}
- Similarity Score: {similarity_score}%
- Match Type: {match_type}

III. EVIDENCE SUMMARY
- Perceptual Hash Similarity: {hash_similarity}%
- Embedding Similarity: {embedding_similarity}%
- AI Analysis Confidence: {ai_confidence}%
- Risk Level: {risk_level}

IV. GOOD FAITH STATEMENT
I have a good faith belief that use of the copyrighted material described
above is not authorized by the copyright owner, its agent, or the law.

V. ACCURACY STATEMENT
The information in this notification is accurate, and under penalty of
perjury, I am authorized to act on behalf of the owner of the copyright
that is allegedly infringed.

VI. REQUESTED ACTION
Please remove or disable access to the infringing material identified above
within the time frame required by applicable law.

Sincerely,
{rights_holder}
Generated by AEGIS Digital Asset Protection Platform
"""

CEASE_DESIST_TEMPLATE = """CEASE AND DESIST NOTICE

Date: {date}
Reference: AEGIS-{ref_id}

Dear {platform} Content Team,

This letter serves as formal notice that copyrighted sports media content
owned by {rights_holder} has been identified on your platform without
authorization.

INFRINGING CONTENT:
- Location: {infringing_url}
- Original Asset: {asset_name}
- Detection Confidence: {similarity_score}%

We demand that you immediately:
1. Remove the infringing content
2. Preserve all records related to the upload
3. Provide information about the uploader

Failure to comply may result in legal action under applicable copyright law.

{rights_holder}
Powered by AEGIS — Digital Asset Intelligence Platform
"""


class EnforcementService:

    @staticmethod
    def generate_dmca(
        asset_name: str,
        description: str,
        registration_date: str,
        rights_holder: str,
        infringing_url: str,
        platform: str,
        detection_date: str,
        similarity_score: float,
        hash_similarity: float,
        embedding_similarity: float,
        match_type: str,
        risk_level: str,
        ref_id: str = "",
    ) -> str:
        """Generate a DMCA takedown notice."""
        return DMCA_TEMPLATE.format(
            date=datetime.now(timezone.utc).strftime("%B %d, %Y"),
            ref_id=ref_id or datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S"),
            asset_name=asset_name,
            description=description or "Sports media content",
            registration_date=registration_date,
            rights_holder=rights_holder or "Rights Holder",
            infringing_url=infringing_url or "N/A",
            platform=platform or "Unknown Platform",
            detection_date=detection_date,
            similarity_score=round(similarity_score * 100, 1),
            hash_similarity=round(hash_similarity * 100, 1),
            embedding_similarity=round(embedding_similarity * 100, 1),
            match_type=match_type,
            ai_confidence=round(similarity_score * 100, 1),
            risk_level=risk_level,
        )

    @staticmethod
    def generate_cease_desist(
        asset_name: str,
        rights_holder: str,
        infringing_url: str,
        platform: str,
        similarity_score: float,
        ref_id: str = "",
    ) -> str:
        return CEASE_DESIST_TEMPLATE.format(
            date=datetime.now(timezone.utc).strftime("%B %d, %Y"),
            ref_id=ref_id or datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S"),
            asset_name=asset_name,
            rights_holder=rights_holder or "Rights Holder",
            infringing_url=infringing_url or "N/A",
            platform=platform or "Unknown Platform",
            similarity_score=round(similarity_score * 100, 1),
        )

    @staticmethod
    def build_evidence_package(
        asset_data: dict,
        match_data: dict,
        risk_data: dict,
    ) -> dict:
        """Build a structured evidence package for legal proceedings."""
        return {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "platform": "AEGIS Digital Asset Intelligence",
            "original_asset": {
                "name": asset_data.get("name", ""),
                "registration_date": asset_data.get("uploaded_at", ""),
                "file_type": asset_data.get("file_type", ""),
                "perceptual_hashes": {
                    "phash": asset_data.get("phash", ""),
                    "ahash": asset_data.get("ahash", ""),
                    "dhash": asset_data.get("dhash", ""),
                    "whash": asset_data.get("whash", ""),
                },
                "ai_description": asset_data.get("gemini_description", ""),
            },
            "violation": {
                "source_url": match_data.get("source_url", ""),
                "platform": match_data.get("platform", ""),
                "detected_at": match_data.get("detected_at", ""),
                "similarity_score": match_data.get("similarity_score", 0),
                "hash_similarity": match_data.get("hash_similarity", 0),
                "embedding_similarity": match_data.get("embedding_similarity", 0),
                "match_type": match_data.get("match_type", ""),
            },
            "risk_assessment": risk_data,
        }
